name: model-wine-quality
on: [push]
jobs:
    run:
      runs-on: ubuntu-latest
      # optionally use a convenient Ubuntu LTS + DVC + CML image
      # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
      steps:
        - uses: iterative/setup-cml@v1
        - uses: navikt/github-app-token-generator@v1
          id: get-token
          with:
            private-key: ${{ secrets.CML_GITHUB_APP_PEM }}
            app-id: ${{ secrets.CML_GITHUB_APP_ID }}
        - uses: actions/checkout@v3
          with:
            ref: ${{ github.event.pull_request.head.sha }}
            token: ${{ steps.get-token.outputs.token }}
        - name: Train model
          env:
            REPO_TOKEN: ${{ steps.get-token.outputs.token }}
        # - uses: actions/checkout@v2
        # may need to setup NodeJS & Python3 on e.g. self-hosted
        # - uses: actions/setup-node@v2
        #   with:
        #     node-version: '16'
        # - uses: actions/setup-python@v2
        #   with:
        #     python-version: '3.x'
        # - name: Train model
          run: |
            # Your ML workflow goes here
            pip install -r requirements.txt
            python train.py

            echo "## Model metrics" > report.md
            cat metrics.txt >> report.md

            echo "## Data viz" > report.md
            cml-publish feature_importance.png --md >> report.md
            cml-publish residuals.png --md >> report.md

            cml send-comment report.md

